// ABO(Amazon Berkeley Objects) 큐레이션 — 실제 제품 이미지(누끼) + 정형 치수(inch→cm). CC BY-NC 4.0.
export const ABO = [
  { id: "abo-81XhyZvD1L", name: "Amazon Brand – Rivet Bristol Natural E", cat: "테이블", w: 48, d: 46, h: 48, color: "#c9bfa8", lowBox: true, image: "/abo/81XhyZvD1L.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-61LgxujFuOL", name: "Amazon Brand – Ravenna Home Angela Mod", cat: "테이블", w: 112, d: 56, h: 51, color: "#c9bfa8", lowBox: true, image: "/abo/61LgxujFuOL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-71rYJhm4VeL", name: "Marchio Amazon - Alkove Hayes - Tavolo", cat: "테이블", w: 130, d: 90, h: 77, color: "#c9bfa8", lowBox: true, image: "/abo/71rYJhm4VeL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-81ucGjQVjL", name: "Amazon Brand - Solimo Mars Engineered ", cat: "테이블", w: 43, d: 36, h: 46, color: "#c9bfa8", lowBox: true, image: "/abo/81ucGjQVjL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-71TbO0FkKL", name: "AmazonBasics LeatherSoft Kids/Youth Re", cat: "의자", w: 70, d: 68, h: 70, color: "#b0a68c", lowBox: true, image: "/abo/71TbO0FkKL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-61WTOkHRcZL", name: "Amazon Brand Movian Dofsan Chair 100 x", cat: "의자", w: 100, d: 93, h: 86, color: "#b0a68c", lowBox: true, image: "/abo/61WTOkHRcZL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-91X8Y0xhyL", name: "Amazon Brand – Stone & Beam Norah Leat", cat: "의자", w: 100, d: 100, h: 44, color: "#b0a68c", lowBox: true, image: "/abo/91X8Y0xhyL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-91udGka1EiL", name: "AmazonBasics Classic Faux Leather Extr", cat: "의자", w: 95, d: 83, h: 98, color: "#b0a68c", lowBox: true, image: "/abo/91udGka1EiL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-81KZp1brWYL", name: "Amazon Brand – Rivet Eva Mid-Century M", cat: "소파", w: 221, d: 90, h: 77, color: "#8fa3b0", lowBox: true, image: "/abo/81KZp1brWYL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-71uyDyjQcL", name: "ROSSINI CANOVA 3 SEATER MAXI", cat: "소파", w: 233, d: 102, h: 93, color: "#8fa3b0", lowBox: true, image: "/abo/71uyDyjQcL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-81yiaE45jL", name: "Amazon Brand - Movian Ribe - Divano a ", cat: "소파", w: 200, d: 92, h: 85, color: "#8fa3b0", lowBox: true, image: "/abo/81yiaE45jL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-71YMq06qWL", name: "Amazon Brand – Stone & Beam Westview E", cat: "소파", w: 226, d: 107, h: 80, color: "#8fa3b0", lowBox: true, image: "/abo/71YMq06qWL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-81cVhl8HXmL", name: "Stone & Beam Tisbury Nailhead Trim Que", cat: "침대", w: 234, d: 168, h: 142, color: "#b8a58a", lowBox: true, image: "/abo/81cVhl8HXmL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-91qktrcsWgL", name: "Amazon Brand – Stone & Beam Tisbury Na", cat: "침대", w: 234, d: 168, h: 142, color: "#b8a58a", lowBox: true, image: "/abo/91qktrcsWgL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-81bMJUjFF5L", name: "AmazonBasics Adjustable Bed Base with ", cat: "침대", w: 203, d: 152, h: 36, color: "#b8a58a", lowBox: true, image: "/abo/81bMJUjFF5L.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-91SZBS938jL", name: "Amazon Brand – Stone & Beam Prudence T", cat: "침대", w: 234, d: 213, h: 142, color: "#b8a58a", lowBox: true, image: "/abo/91SZBS938jL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-81oTHF1PcUL", name: "Amazon Brand – Stone & Beam Modern Cry", cat: "조명", w: 30, d: 30, h: 46, color: "#cfc4ad", lowBox: false, image: "/abo/81oTHF1PcUL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-418eXzxGlSL", name: "Amazon Brand – Rivet Dome-Shaped Table", cat: "조명", w: 33, d: 33, h: 23, color: "#cfc4ad", lowBox: false, image: "/abo/418eXzxGlSL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-61pDBxYvDBL", name: "Umi. by Amazon - Lámpara de pie, panta", cat: "조명", w: 35, d: 35, h: 144, color: "#cfc4ad", lowBox: false, image: "/abo/61pDBxYvDBL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-41gZ0BM3dnL", name: "Amazon Brand – Ravenna Home Glass Stac", cat: "조명", w: 42, d: 42, h: 40, color: "#cfc4ad", lowBox: false, image: "/abo/41gZ0BM3dnL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-814WJICrXwL", name: "Vida Designs Corona Wardrobe, 3 Door, ", cat: "수납", w: 150, d: 50, h: 178, color: "#d0c3a8", lowBox: true, image: "/abo/814WJICrXwL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-81Run7yoRL", name: "Marchio Amazon - Movian, credenza a 2 ", cat: "수납", w: 100, d: 40, h: 119, color: "#d0c3a8", lowBox: true, image: "/abo/81Run7yoRL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-71S7YSK7NL", name: "Amazon Brand – Stone & Beam Mid-Centur", cat: "수납", w: 55, d: 39, h: 60, color: "#d0c3a8", lowBox: true, image: "/abo/71S7YSK7NL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-911EiPQpzgL", name: "Amazon Brand – Rivet Mid-Century Stark", cat: "수납", w: 155, d: 46, h: 81, color: "#d0c3a8", lowBox: true, image: "/abo/911EiPQpzgL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-71o41o39HL", name: "Amazon Brand – Ravenna Home Springdale", cat: "책상", w: 76, d: 34, h: 183, color: "#c9b79a", lowBox: true, image: "/abo/71o41o39HL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-610yeWPoveL", name: "Amazon Brand - Movian Mjøsa - Compact ", cat: "책상", w: 79, d: 44, h: 76, color: "#c9b79a", lowBox: true, image: "/abo/610yeWPoveL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-71arjf0rbxL", name: "Amazon Brand – Rivet Classic Desk, 39.", cat: "책상", w: 100, d: 55, h: 76, color: "#c9b79a", lowBox: true, image: "/abo/71arjf0rbxL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-81HI2CE9kL", name: "Amazon Brand – Stone & Beam Casual Woo", cat: "책상", w: 152, d: 76, h: 76, color: "#c9b79a", lowBox: true, image: "/abo/81HI2CE9kL.png", dimAccuracy: "정형", source: "ABO" },
  { id: "abo-A1YgjsRfRuL", name: "nuLOOM Rikki Braided Border Jute Area ", cat: "러그", w: 152, d: 20, h: 20, color: "#d8cdbb", lowBox: true, image: "/abo/A1YgjsRfRuL.png", dimAccuracy: "정형", source: "ABO" },
];
